# [Formatter] - black 
[tool.black]
line-length = 88


# [Type-Checking] - mypy 
[tool.mypy]

[[tool.mypy.overrides]]
module = ["cv2", "PIL", "matplotlib", "torchvision.*"]
ignore_missing_imports = true


# [Linter] - pylint
[tool.pylint."MESSAGES CONTROL"]
disable = [
  "line-too-long",
  "redefined-outer-name",
  "C0114",                # missing-module-docstring
  "no-member",
  "consider-using-with",
  "import-error",
]
