# [Formatter] - black 
[tool.black]
line-length = 88


# [Type-Checking] - mypy 
[tool.mypy]
ignore_missing_imports = true


# [Linter] - pylint
[tool.pylint."MESSAGES CONTROL"]
disable = [
  "line-too-long",
  "redefined-outer-name",
  "C0114",                         # missing-module-docstring
  "no-member",
  "consider-using-with",
  "import-error",
  "too-many-locals",
  "too-many-arguments",
  "invalid-name",
  "wrong-import-position",
  "no-name-in-module",
  "unnecessary-lambda-assignment",
  "dangerous-default-value",
]
[tool.pylint."SIMILARITIES"]
min-similarity-lines = 30
