# Paths of input and output folder. Relative to this file or absolute.
input: ../../data/WLASL/videos
output: ../../data/WLASL/labeled_frames
wlasl_config: "../../data/WLASL/info.json"
number_labels: all # "all", number
