# Paths of input and output folder. Relative to this file or absolute.
input: ../../data/WLASL/videos
output: ../../data/WLASL/frames
wlasl_config: "../../data/WLASL/info.json"
number_labels: all # "all", number
number_frames: 5 # "all", number
merge_frames: False # True, False
